server:
  port: 8083
  servlet:
    session:
      timeout: 25200 # session超时时间为25200秒=7天


spring:
  rabbitmq:
    port: 5672
    host: 192.168.10.7
    username: guest
    password: guest
    template:
      #mandatory 参数设为 true 时，交换器无法根据自身的类型和路由键找到一个符合条件的队列，
      #那么 RabbitMQ 会调用 Basic.Return 命令将消息返回给生产者 。
      #mandatory数设置为 false 时，出现上述情形，则消息直接被丢弃
      mandatory: true
      exchange: demo-fanout
    #通过实现 ReturnCallback 接口，启动消息失败返回，比如路由不到队列时触发回调,该模式会在消息没有被路由到queues时将消息返回
    publisher-returns: true
    #通过实现 ConfirmCallback 接口，消息发送到 Broker 后触发回调，确认消息是否到达 Broker 服务器，也就是只确认是否正确到达 Exchange 中
    publisher-confirm-type: correlated


