eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      default-zone: http://${eureka.instance.hostname}:${server.port}/eureka
  instance:
    hostname: localhost
  server:
    enable-self-preservation: true
    renewal-percent-threshold: 0.5
server:
  port: 8077
spring:
  application:
    name: eureka-server